kumuluzee:
  name: libraryservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8083
  datasources:
  - jndi-name: jdbc/libraryservice
    connection-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: skiprope
    pool:
      max-size: 2

  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/libraryservice
      disk-space-health-check:
        threshold: 100000000

  metrics:
    web-instrumentation:
      - name: all-endpoints
        url-pattern: /api/*
    servlet:
      enabled: true

  discovery:
    etcd:
      hosts: http://localhost:2379

  config:
    etcd:
      hosts: http://localhost:2379

# Settings and configurations
skiprope-configs:
  health:
    etcd-url: http://localhost:2379/health